### ISSUE TITLE
Do you mind adding English explanation?

### ISSUE THREAD

**Issue by robot-Yang** [gonzafernan/self-balancing-lqg#3]
Hi,

Your project is very interesting to me (I believe also interesting to other people).  But do you mind adding English explanation?

Thanks.

**Comment by gonzafernan** [comment]
Thanks for showing interest in the project! Of course, I'll translate the code and later I'll try to upload an english version of the report presented in the RPIC 2021 congress.

**Comment by gonzafernan** [comment]
I have already translated the code and the models into english. Let me know if you find any error or something is not easy to understand. Thanks again for the proposal!

The translation of the report is pending, so I don't close the issue.

**Comment by robot-Yang** [comment]
Thank you so much for your effort! I will check the code and let you know if there is any problem. Also, thanks for translating the report, it will be very helpful as well.

**Comment by gonzafernan** [comment]
Hi @robot-Yang, it took some time for me to do it but it's done :smile: Here it's the report translated to english [control_theory-report-en.pdf](https://github.com/gonzafernan/self-balancing-lqg/blob/master/docs/control_theory-report-en.pdf)
